- name: "------------------------- Install Apache ---------------------------"
  yum: pkg=httpd state=present

- name: "Virtualhost config file"
  copy: src=files/vhost.conf dest=/etc/httpd/conf.d/vhost.conf

- name: "Create default PHP info"
  copy: src=files/index.php dest=/var/www/html/index.php

- name: "Restart Apache"
  service: name=httpd state=restarted
