  - name: "---------------------- Install PHP7 ------------------------"
    yum: name={{ item }} state=present
    with_items:
      - php70w
      - php70w-cli
      - php70w-pdo
      - php70w-mysql

  - name: "Install composer - check if installed"
    stat: "path=/usr/local/bin/composer"
    register: composer_bin

  - name: "Install composer - download"
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer_installer.php
    when: not composer_bin.stat.exists

  - name: "Install composer - execution"
    shell: /usr/bin/php /tmp/composer_installer.php --install-dir=/usr/local/bin --filename=composer
    when: not composer_bin.stat.exists

  - name: "Install composer - clean up"
    file: path=/tmp/composer_installer.php state=absent
    when: not composer_bin.stat.exists
